const fs = require('fs');

const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_KEY || '';
const discordGuildId = process.env.DISCORD_GUILD_ID || '';

const configContent = `// Automatically generated by generate-config.js at build time
window.SUPABASE_CONFIG = {
    url: "${url}",
    key: "${key}",
    discordGuildId: "${discordGuildId}"
};
`;

fs.writeFileSync('./supabase-config.js', configContent);
console.log('Successfully generated supabase-config.js with build-time environment variables.');
