-- =======================================================
-- Supabase Schema for THC Labs Gaming Portal (Prefix: thc_)
-- Run this in your Supabase SQL Editor
-- =======================================================

-- 1. Chat Messages Table
create table if not exists thc_chat_messages (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    username text not null,
    color text not null,
    message text not null
);

-- 2. Gaming Events Table
create table if not exists thc_gaming_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    event_date text not null,
    platform text not null,
    description text
);

-- 3. Pixel Board Table (Holds 32x32 color grid)
create table if not exists thc_pixel_board (
    id bigint primary key,
    pixels jsonb not null
);

-- Initialize the Pixel Board with empty grid (1024 black pixels) if not exists
insert into thc_pixel_board (id, pixels)
values (1, '[]')
on conflict (id) do nothing;

-- 4. Enable Row Level Security (RLS) on all tables
alter table thc_chat_messages enable row level security;
alter table thc_gaming_events enable row level security;
alter table thc_pixel_board enable row level security;

-- 5. Create Public Policies (Anonymous Read/Write access)

-- Chat messages policies
create policy "Allow public read access to chat"
on thc_chat_messages for select
using (true);

create policy "Allow public inserts to chat"
on thc_chat_messages for insert
with check (true);

-- Gaming events policies
create policy "Allow public read access to events"
on thc_gaming_events for select
using (true);

create policy "Allow public inserts to events"
on thc_gaming_events for insert
with check (true);

create policy "Allow public deletions of events"
on thc_gaming_events for delete
using (true);

-- Pixel board policies
create policy "Allow public read access to pixel board"
on thc_pixel_board for select
using (true);

create policy "Allow public updates of pixel board"
on thc_pixel_board for update
using (true);

create policy "Allow public inserts of pixel board"
on thc_pixel_board for insert
with check (true);


-- ==========================================
-- 6. SnapChat THC Tables
-- ==========================================

-- Tabla de Fotos (Snaps)
create table if not exists thc_snap_photos (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    username text not null,
    room_code text not null,
    image_data text not null, -- Base64 encoded or image url
    caption text,
    recipient text default 'group' not null, -- 'group' or specific username
    likes_count integer default 0 not null,
    likes_by jsonb default '[]'::jsonb not null
);

-- Tabla de Rachas (Streaks)
create table if not exists thc_snap_streaks (
    id bigint generated by default as identity primary key,
    room_code text not null,
    user_a text not null,
    user_b text not null, -- 'group' or another username
    streak_count integer default 0 not null,
    last_posted date default current_date not null,
    unique (room_code, user_a, user_b)
);

-- ==========================================
-- 7. Trivia THC Tables
-- ==========================================

-- Tabla de Preguntas de Trivia
create table if not exists thc_trivia_questions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    question text not null,
    options jsonb not null, -- array of strings: ["A", "B", "C", "D"]
    correct_index integer not null, -- index of correct option: 0 to 3
    category text default 'General' not null,
    creator text default 'Sistema' not null
);

-- Tabla de Clasificación de Trivia
create table if not exists thc_trivia_leaderboard (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    username text not null,
    score integer not null,
    correct_answers integer not null,
    total_questions integer not null
);

-- Enable RLS
alter table thc_snap_photos enable row level security;
alter table thc_snap_streaks enable row level security;
alter table thc_trivia_questions enable row level security;
alter table thc_trivia_leaderboard enable row level security;

-- Policies for SnapChat
create policy "Allow public read access to snaps" on thc_snap_photos for select using (true);
create policy "Allow public inserts of snaps" on thc_snap_photos for insert with check (true);
create policy "Allow public updates of snaps" on thc_snap_photos for update using (true);

create policy "Allow public read access to streaks" on thc_snap_streaks for select using (true);
create policy "Allow public inserts of streaks" on thc_snap_streaks for insert with check (true);
create policy "Allow public updates of streaks" on thc_snap_streaks for update using (true);

-- Policies for Trivia
create policy "Allow public read access to trivia_questions" on thc_trivia_questions for select using (true);
create policy "Allow public inserts of trivia_questions" on thc_trivia_questions for insert with check (true);

create policy "Allow public read access to trivia_leaderboard" on thc_trivia_leaderboard for select using (true);
create policy "Allow public inserts of trivia_leaderboard" on thc_trivia_leaderboard for insert with check (true);

