-- =======================================================
-- Supabase Schema for THC Labs Gaming Portal (Prefix: thc_)
-- Run this in your Supabase SQL Editor
-- =======================================================

-- 1. Chat Messages Table
create table if not exists thc_chat_messages (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    username text not null,
    color text not null,
    message text not null
);

-- 2. Gaming Events Table
create table if not exists thc_gaming_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    event_date text not null,
    platform text not null,
    description text
);

-- 3. Pixel Board Table (Holds 32x32 color grid)
create table if not exists thc_pixel_board (
    id bigint primary key,
    pixels jsonb not null
);

-- Initialize the Pixel Board with empty grid (1024 black pixels) if not exists
insert into thc_pixel_board (id, pixels)
values (1, '[]')
on conflict (id) do nothing;

-- 4. Enable Row Level Security (RLS) on all tables
alter table thc_chat_messages enable row level security;
alter table thc_gaming_events enable row level security;
alter table thc_pixel_board enable row level security;

-- 5. Create Public Policies (Anonymous Read/Write access)

-- Chat messages policies
create policy "Allow public read access to chat"
on thc_chat_messages for select
using (true);

create policy "Allow public inserts to chat"
on thc_chat_messages for insert
with check (true);

-- Gaming events policies
create policy "Allow public read access to events"
on thc_gaming_events for select
using (true);

create policy "Allow public inserts to events"
on thc_gaming_events for insert
with check (true);

create policy "Allow public deletions of events"
on thc_gaming_events for delete
using (true);

-- Pixel board policies
create policy "Allow public read access to pixel board"
on thc_pixel_board for select
using (true);

create policy "Allow public updates of pixel board"
on thc_pixel_board for update
using (true);

create policy "Allow public inserts of pixel board"
on thc_pixel_board for insert
with check (true);
